---
title: "Projects"
format: html
editor: visual
---

* [Employment Equity: An Analysis of Distribution of Salary Ranges of Public Service of Canada Employees](https://klaxonklaxoff.github.io/ee_dv/)\
    [{code}](https://github.com/klaxonklaxoff/ee_dv)\
    Code used to webscrape and visualize employee salary data from the Government of Canada's Treasury Board. Here we demonstrate systemic disadvantage in career progression amongst Black public servants which must be resolved with a strategic plan to identify structural and systemic barriers and improve retention and success to levels achieved by their non-racialized peers.

* [Making a Research Website with Github and Hugo](https://github.com/alburycatalina/Personal-Research-Website)\
  A tutorial for making a personal research website with Github and Hugo.


* [Planet aRt](https://github.com/alburycatalina/planet-aRt)\
 [{code}](https://github.com/alburycatalina/planet-aRt/blob/main/planet-aRt.R)\
My attempt at making some pretty things with the generative art package, aRtsy.

* [Thesis Word Cloud](https://github.com/alburycatalina/ThesisWordCloud)\
  [{code}](https://github.com/alburycatalina/ThesisWordCloud/blob/main/thesis_wordcloud.R)\
  A quick little repo containing a script I used to create a word cloud from my thesis. Here I make a visually appealing representation of the frequency of words used to tell the story of what I've been working on for the past two and a half years. 


* [Coding Nature](https://github.com/alburycatalina/Coding-Nature)\
  A repository for a workshop for Black high school students in Nova Scotia (ages 13+). This workshop aims to inspire passion for nature and science, while giving an introduction to coding logic and data. The included exercises demonstrate how we can use programming as a tool to improve our understanding of the world around us.

* [Intro to Coding for Sr. High](https://github.com/alburycatalina/FHA_intro_to_coding)\
  Code for a 2-day introductory coding tutorial for Bahamian high school students at Forest Heights Academy. 
