---
title: "Publications"
format: html
editor: visual
---



### In Progress
Complex proteomic rearrangements in response to vitamin B12 starvation and heat stress in the polar diatom, *F. cylindrus*. **Catalina Albury**, Elden Rowland, Erin Bertrand

### 2023
[Exploring Career Stagnation In Employment Equity Groups Amongst Canadian Public Servants.](https://www.isi2023.org/abstracts/submission/617/view/) 2023. **Catalina Albury**, Brittny Vongdara, Shamir Kanji, Martin Nicholas. *ISI WSC Conference Proceedings.* [(PDF)](https://www.isi2023.org/media/abstracts/ottawa-2023_a4304726a4ffc04552129532cf656303.pdf)


### 2022

[Collaborative Enhancement of Canadian and West African Partner Countries' Technical Capacity for a Safe, Secure, and Sustainable Blue Economy](https://www.thejot.net/article-preview/?show_article_preview=1389). 2022. Debany Fonseca-Batista, **Catalina Albury**, Simone Le Gendre, Chukwuka Orji, Alberta Ama Sagoe, Christopher Milley, Kenneth Oguzie, Raffaella Gozzelino, Douglas Wallace. *The Journal of Ocean Technology*. [(PDF)](https://www.thejot.net/article-preview/?show_article_preview=1389&jot_download_article=1389)


[MSc Thesis: The Molecular Consequences of Vitamin B12 Deprivation in the Polar Diatom](https://dalspace.library.dal.ca/handle/10222/81567), *Fragilariopsis cylindrus*. 2022. **Catalina Albury**. [(PDF)](https://dalspace.library.dal.ca/bitstream/handle/10222/81567/CatalinaAlbury2022.pdf?sequence=1&isAllowed=y)

### 2021

[Ecology and evolutionary biology must elevate BIPOC scholars](https://onlinelibrary.wiley.com/doi/abs/10.1111/ele.13716). 2021. Melanie Massey, Suchinta Arif, **Catalina Albury**, Victoria Cluney. *Ecology Letters* [(PDF)](https://onlinelibrary.wiley.com/doi/epdf/10.1111/ele.13716)

[Ten Simple Rules for Supporting Historically Underrepresented Students in Science](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009313). 2021. Suchinta Arif, Melanie Massey, Natalie Klinard, Julie Charbonneau, Loay Jabre, Ana Barbosa Martins, Danielle Gaitor, Rhiannon Kirton, **Catalina Albury**, Karma Nanglu. *PLoS Computational Biology*.  [(PDF)](https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1009313&type=printable)

### 2019

[Honours Thesis: The Effects of Vitamin B12 Starvation on Heat Resistance in *Fragilariopsis cylindrus*](https://www.researchgate.net/publication/336720705_Effects_of_Vitamin_B12_Starvation_on_Heat_Resistance_in_Fragilariopsis_Cylindrus). 2019.  **Catalina Albury**. [(PDF)](https://www.researchgate.net/publication/360068994_The_Molecular_Consequences_of_Vitamin_B12_Deprivation_in_the_Polar_Diatom_Fragilariopsis_cylindrus)
